# Generated by Django 5.2 on 2025-04-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pay_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('on_completion', 'On Completion')], default='daily', max_length=20)),
                ('worker_type', models.CharField(max_length=100)),
                ('num_workers_needed', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=50)),
            ],
        ),
    ]
